# Класс, который будет использоваться для получения данных
# (двоеточие означает сокращение для tabun_stat.datasource)
name = ":sqlite3.Sqlite3DataSource"
# Остальные параметры передаются в конструктор этого класса как есть
path = "./demo.sqlite3"
